# -*- coding: utf-8 -*-
"""Untitled39.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1omoB5dujG630Y7GjZGST_pkLURILm7KY
"""

import torch
from diffusers import StableDiffusionPipeline
import os
import matplotlib.pyplot as plt


model_id = "runwayml/stable-diffusion-v1-5"

print("Loading the model... this may take a minute.")
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)

# Move the model to GPU for faster generation
pipe = pipe.to("cuda")
print("Model loaded successfully!")


prompts = [
    "A futuristic city with flying cars and neon lights, cyberpunk style",
    "A cute astronaut cat exploring Mars, high detail, 4k",
    "A serene lake surrounded by snowy mountains at sunset",
    "A robot painting a canvas in an art studio, oil painting style",
    "A medieval castle floating on a cloud, fantasy art"
]


output_folder = "synthetic_dataset"
os.makedirs(output_folder, exist_ok=True)

generated_images = []

print(f"\nStarting generation of {len(prompts)} images...")

for i, prompt in enumerate(prompts):
    print(f"Generating sample {i+1}: {prompt}")

    # Generate the image
    # We use a distinct seed for reproducibility (optional but good practice)
    generator = torch.Generator("cuda").manual_seed(1024 + i)
    image = pipe(prompt, generator=generator).images[0]

    # Save generated output in the folder
    file_path = f"{output_folder}/generated_sample_{i+1}.png"
    image.save(file_path)

    # Store in list for display
    generated_images.append((prompt, image))

print(f"\nAll images have been saved to the '{output_folder}' directory.")

# ==========================================
# 4. DISPLAY SAMPLE OUTPUTS
# ==========================================
# Display the generated samples as required
plt.figure(figsize=(20, 5))

for i, (prompt, img) in enumerate(generated_images):
    plt.subplot(1, 5, i+1)
    plt.imshow(img)
    plt.axis('off')
    plt.title(f"Sample {i+1}")

plt.show()

# Print the text mapping
for i, prompt in enumerate(prompts):
    print(f"Sample {i+1}: {prompt}")

import torch
from diffusers import StableDiffusionPipeline
import os
import shutil

# ==========================================
# 1. SETUP MODEL
# ==========================================
model_id = "runwayml/stable-diffusion-v1-5"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipe = pipe.to("cuda")

# ==========================================
# 2. DEFINE CATEGORIES AND PROMPTS
# ==========================================
# We map your specific categories to detailed prompts to get the best X-ray look.
# Key = The Folder Name (Label)
# Value = The Prompt for the AI
data_categories = {
    "Normal_Anatomy": "A high quality medical chest X-ray of healthy lungs, PA view, clear diaphragm, sharp bony structures, monochrome, radiography",

    "Infectious_Patterns": "A chest X-ray showing bacterial pneumonia with lobar consolidation, medical imaging, black and white radiograph",

    "Lung_Opacities": "A chest X-ray showing ground-glass opacities in the lungs, diffuse haziness, medical diagnosis image",

    "Pleural_Conditions": "A chest X-ray showing pleural effusion, fluid accumulation at the lung base, blunted costophrenic angle",

    "Structural_Lesions": "A chest X-ray showing a pulmonary nodule in the right upper lobe, medical screening, high contrast",

    "Cardiac_Findings": "A chest X-ray showing cardiomegaly, enlarged heart silhouette, vascular congestion, medical imaging",

    "Medical_Devices": "A chest X-ray showing a pacemaker implanted in the chest wall with leads extending to the heart, medical device artifact",

    "Imaging_Artifacts": "A low quality chest X-ray with motion blur and noise, poor exposure, medical imaging artifact",

    "View_Positioning": "A chest X-ray, AP view, patient in supine position, portable X-ray machine quality",

    "Domain_Shift": "A chest X-ray scanned from a film, different hospital protocol, slightly different contrast resolution"
}

# ==========================================
# 3. GENERATE AND SAVE WITH LABELS
# ==========================================
base_folder = "synthetic_xray_dataset"

# Clean up previous run if it exists
if os.path.exists(base_folder):
    shutil.rmtree(base_folder)
os.makedirs(base_folder)

print(f"Generating data for {len(data_categories)} categories...\n")

for label, prompt_text in data_categories.items():
    # Create a sub-folder for this specific label (Class)
    # This fulfills the requirement to "give label and image"
    class_folder = os.path.join(base_folder, label)
    os.makedirs(class_folder, exist_ok=True)

    print(f"Processing Category: {label}...")

    # We generate 2 images per category just to show variation
    for i in range(2):
        # Using a generator with a different seed for every image ensures they look different
        generator = torch.Generator("cuda").manual_seed(2024 + i + len(label))

        # Adding "photorealistic, medical x-ray" to every prompt to enforce style
        full_prompt = f"{prompt_text}, photorealistic, medical x-ray style, high definition"

        image = pipe(full_prompt, generator=generator).images[0]

        # Save image: Label_Index.png
        filename = f"{label}_{i+1}.png"
        image.save(os.path.join(class_folder, filename))

print(f"\nSuccess! Dataset created at: {base_folder}")

# ==========================================
# 4. DISPLAY SAMPLES
# ==========================================
import matplotlib.pyplot as plt

# Pick the first image from 5 categories to display
display_labels = list(data_categories.keys())[:5]

plt.figure(figsize=(20, 5))
for i, label in enumerate(display_labels):
    img_path = os.path.join(base_folder, label, f"{label}_1.png")
    if os.path.exists(img_path):
        img = plt.imread(img_path)
        plt.subplot(1, 5, i+1)
        plt.imshow(img, cmap='gray') # Display in grayscale
        plt.title(label)
        plt.axis('off')

plt.show()